name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.3'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      working-directory: ./tests/e2e
      run: npm ci

    - name: Install Playwright Browsers
      working-directory: ./tests/e2e
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      working-directory: ./tests/e2e
      run: npx playwright test
